### ISSUE TITLE
Un sitio para cada cosa

### ISSUE THREAD

**Issue by DanBaDo** [manulm27/generator_excuses#1]
Vamos a quitar esos arrays de dentro de la función. Intentaremos ordenar el código de la siguiente manera:

1. (no aplicable) requires/imports de código que ajeno a nuestro proyecto (no hace referencia a carpetas o ficheros en el proyecto)
2. (no aplicable) requires/imports de código de nuestro proyecto
3. declaración de variables constantes globales (debería de haber ninguna o las mínimas). Aquí pondremos los array de esta tarea. 
4. declaraciones de funciones (y otras cosas que iremos conociendo)
5. Asignación de manejadores a eventos (addEventListener) y punto de entrada al programa (en este caso, el addEventListener llamando a la función que empieza a tirar del hilo del código).

Ante la duda, ya conoces todas las opciones que tienes para obtener ayuda. ¡Adelante!.

https://github.com/manulm27/generator_excuses/blob/e4d3708ce0122713b27d0fa150f2f2567e6b6b33/src/app.js#L2-L30

**Comment by manulm27** [comment]
Hola Daniel e corregido el código de acuerdo a tus observaciones. Gracias.
